### PR TITLE
Alena 

### PR DESCRIPTION
**Pull request by Aporazava**

### CODE REVIEW

**Review by cherepanovmaxim — CHANGES_REQUESTED** [review]
change

**Comment by Aporazava** [comment]
the test fails at clicking SEND button despite I used Hakan code. Can you check please?

**Review by HakanK003 — APPROVED** [review]
Good job, you may use utilities methods and configuration properties for reusability.

**Comment by Aporazava** [comment]
the tests fail anyway, usually on clicking SEND button, but the location of the button is correct for sure

**Comment by Aporazava** [comment]
ElementClickInterceptedException: element click intercepted: Element <button class="ui-btn ui-btn-lg ui-btn-primary" id="blog-submit-button-save">...</button> is not clickable at point (303, 620). Other element would receive the click: <div class="feed-add-post-expire-date-wrap">...</div>
(Session info: chrome=98.0.4758.82)

**Comment by Aporazava** [comment]
Is it a bug?
Now at office hours there bags too. And My tests stopped at different points as well

**Review by HakanK003 — APPROVED** [review]
good job

**Review by aniqas7 — APPROVED** [review]
good

**Review by aniqas7 — APPROVED** [review]

**Review by HakanK003 — APPROVED** [review]

**Review by cherepanovmaxim — APPROVED** [review]

**Pull request merged**
